# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build:
    desc: Build the gh-task binary
    aliases: [b]
    cmds:
      - go build -o gh-task main.go
      - gh extension remove gh-task
      - gh extension install . --force
    silent: true
